### PR TITLE
Dell 1D3B code

### PR DESCRIPTION
**Pull request by A-syncritus**
Pardon the end-of-line blanks removal - that was done automatically by my editor

### CODE REVIEW

**Comment by persuader** [comment]
I have dell e5430 with service tag - 8B53ZW1-1D3B i have tested with your fork and the generated code does not work. Any ideas what is wrong?

**Comment by bacher09** [comment]
Nice work and sorry for delay. I will upload it in few days.

**Comment by A-syncritus** [comment]
Tnx, try github pages - free hosting and no need to upload.

**Comment by bacher09** [comment]
Unfortunately github pages isn't allow you to use https. Also before upload I will make some additional testing for outdated browsers.

**Comment by yagamilite2016** [comment]
system number : 1szb6r1-1d3b please password

**Comment by moslimbios** [comment]
Biosunlocker.com

**Comment by mikrovr** [comment]
Today, I will release my codes! 
1F5A, 1F66, 3A5B, 6FF1, without any suffix.

**Comment by mikrovr** [comment]
Today, I will release my codes! 
1F5A, 1F66, 3A5B, 6FF1, without any suffix.

**Comment by mikrovr** [comment]
backer09, could publish it for me?

**Comment by loraflores** [comment]
plz do now

**Comment by hamadfethi** [comment]
thanks wher'it the code

**Pull request merged**
